### ISSUE TITLE
Incompatible with v91?

### ISSUE THREAD

**Issue by explor202** [tjeb/Mailbox-Alert#44] opened 2021-10-04 14:34 UTC
I upgraded to v91 yesterday, now none of my custom sounds for individual email accounts are played when new email arrives. Will this add-on be updated so that will work again?

**Comment by AlexUkr73** [comment] 2021-10-15 12:16
Additional issue when "Mailbox Alert" action is defined in TB "Filter Rules".

S c e n a r i o :

1. Mailbox alert ALRT1 is configured in addon setup to show message.
    Clicking "Tests these settings" shows pop-up window (as expected).

2. RULE1 is configured to perform actions on message arrival from certain address:
   a) Move message to defined local Folder;
   b) execute "Mailbox Alert" ALRT1 action.

3. Message from address above is arrived.
E x p e c t e d: Mailbox alert pop-up window is displayed, message is moved to defined Folder.

A c t u a l (problem): Mailbox alert pop-up window does NOT display.
                                Message is moved to defined Folder.

TB 91.2.0 (64 bit), Win10

**Comment by explor202** [comment] 2021-10-23 23:03
@tjeb Could you please respond and let us know if you'll be fixing this or not?

**Comment by tjeb** [comment] 2021-10-26 10:17
The run-from-filter does indeed appear to be broken, not sure what they changed this time, so no idea what is wrong yet and no idea when I will have time to dive into this.

Audio seems fine for me though (if the alert is triggered, that is, like when configured on a folder directly); does the built-in audio alert from thunderbird work?

**Comment by explor202** [comment] 2021-10-26 11:51
I've reverted back to TB 78.14.0 for now. And yes, the standard audio/visual alerts in TB work as expected even when customized.

**Comment by mforkel** [comment] 2021-10-27 08:29
Similar problem here. I have been using an alert that executes Popup (installed from Popup2.zip from the Mailbox Alert website). After the upgrade to Thunderbird 91 filters using that alert fail and terminate the filter run:
```
[27.10.21, 08:30:41] Mitteilung von Filter "<filter name>": Applying filter actions failed

[27.10.21, 08:30:41] Filter run failed
```
I can still run the alert successfully from the alert configuration dialog. 

Environment: Windows 10 Pro 21H1, Thunderbird 91.2.1, Mailbox Alert 0.28

**Comment by tjeb** [comment] 2021-10-28 12:18
I have found the cause of the filter issue and it will be fixed in the next release (headsup: it will require a restart of thunderbird in this specific occasion).

Regarding the original issue reported here, if Mailbox Alert is not working *at all* after the update, you might be running into a completely different issue with addons in general: https://thunderbird.topicbox.com/groups/addons/T9a8b75cbcdf00e44-M0b78ac2ac699055626a7b754

**Comment by explor202** [comment] 2021-10-28 12:40
> 
> 
> I have found the cause of the filter issue and it will be fixed in the next release (headsup: it will require a restart of thunderbird in this specific occasion).
> 
Thanks for the update tjeb. When will you release the updated version?

**Comment by explor202** [comment] 2021-11-01 13:50
@tjeb I see the changelog shows this has been updated to v 0.29, but when I try to install from the zip, TB 91.2.1 says it's corrupt. Is 0.29 ready to install?

**Comment by tjeb** [comment] 2021-11-02 08:03
No, I updated the version to submit it, but it didn't pass review, so I need to address the comments first.

**Comment by tjeb** [comment] 2021-11-08 10:05
0.29.1 did pass review and has been published.

**Comment by explor202** [comment] 2021-11-08 13:08
@tjeb this still doesn't work for me. I tested on a Win 8.1 PC and Win 10 laptop. The PC doesn't fire the script and the laptop doesn't play the custom sound.

**Comment by tjeb** [comment] 2021-11-08 13:21
Do you get any mailbox-alert related messages in the error console? (ctrl-shift-j or tools->developer tools->error console)

**Comment by explor202** [comment] 2021-11-08 13:24
Please disregard. I forgot that a restart of TB was needed after updating the add-on. I just did that and the script fired as expected on the PC. I'll test the laptop later but expect the same results.

**Closed as completed** 2021-11-09 12:54 UTC
